services:
  ollama:
    build: ./ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - ollama
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0