services:
  ollama:
    build: ./ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - ollama
    ports:
      - "7860:7860"
    volumes:
      - ./app:/app
